
services:
  web:
    build: TodoApp
    command: gunicorn TodoApp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY=your-secret-key