apiVersion: v1
kind: Secret
metadata:
  name: todoapp-secret
type: Opaque
data:
  # Generate with: echo -n 'your-secret-key' | base64
  SECRET_KEY: "ZGphbmdvLWluc2VjdXJlLTdzdDkoNXE4PSYhOHAwMD1hMWtAY2VrKWwoMzk5QF9wZih6ZSR3emwxczhhK2MkZGtn"

  # If using database (optional)
  DB_PASSWORD: "base64-encoded-password="