apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  labels:
    app: todoapp
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
    - name: http
      protocol: TCP
      port: 8000          # Service port
      targetPort: 8000    # Container port
      nodePort: 30080     # Matches kind-config.yaml (accessible via localhost:8000)